### ISSUE TITLE
Loading on "Explore" forever

### ISSUE THREAD

**Issue by turion** [jefgodesky/thefifthworld-react#26]
When I go to http://165.22.1.164/rpg, there is a loading animation in green (stark contrast to the color scheme of the site) which never stops.

**Comment by turion** [comment]
After a few minutes and a few reloads, it now displays a map. That map still takes a long time to load (several seconds), and the loading animation doesn't look very nice. I'd recommend at least adding a soft-focus pre-rendered map as background during loading.

**Comment by jefgodesky** [comment]
Hmmm. This is a tricky one. The base map loads pretty quick, but there’s also a GeoJSON mask that raises the sea levels, and that’s pretty big. I had the base map loading, and then the sea levels would rise whenever the GeoJSON finished loading, but that was pretty weird. It might be that we can prioritize some GeoJSON over others, but honestly I don’t know the format well enough to even start on that...

**Comment by jefgodesky** [comment]
You did mean http://165.22.1.164/explore for the URL, right?

**Comment by turion** [comment]
Yes, that's URL I meant.

**Comment by jefgodesky** [comment]
#10 could ameliorate this, but it won't solve it.

**Comment by jefgodesky** [comment]
I just uploaded a change to how the loading is handled. There's not much we can do to actually make it load any faster, but hopefully this makes it a little easier to see that there's something happening. If you try it out, I'd love to hear what you think.

**Comment by turion** [comment]
Ok, that did load a lot faster! I'm now stuck for a long time at "Melting ice caps", which gives me a slightly uneasy feeling, but I guess if that caption would be in the right bottom corner or top middle, and smaller and more transparent, that would look awesome!

**Comment by jefgodesky** [comment]
Well, the base map loads pretty fast, but it’s not accurate — the “Melting ice caps” needs to stay in the middle so you know that the map doesn’t actually work yet. You’ll notice some massive changes to the coastlines when it finishes. If you start using the map, and then the coastlines fill in and the thing you were just looking at suddenly turns blue because it’s all underwater now, that’s really confusing. It seems like waiting for it to load is better than wondering what the heck happened and if it all suddenly broke, right?

**Comment by jefgodesky** [comment]
Well, at least we're not getting that loading message on location pages any more.
